runtime:
  chains: ["solana"]
  lookback_minutes: 180

filters:
  min_liquidity: 5000
  min_volume_24h: 1000
  min_fdv: 50000
  max_fdv: 10000000
  min_avg_txn: 5

blacklists:
  coins: []          # сюда будут добавляться “плохие” монеты
  developers: []     # сюда будут добавляться разработчики с рог-пул монет

pocket_universe:
  enabled: false
  url: ""
  api_key: ""

sources:
  dexscreener:
    base_url: "https://api.dexscreener.io/latest/dex"
  pumpfun:
    base_url: "https://pump.fun/api"

storage:
  url: "sqlite:///alpha_hunter.db"
  echo_sql: false

telegram:
  enabled: true
  bot_token: "8259199756:AAFrBeTEIS-H5mmuiFYnlb2M-anuu3_F84s"  # вставь токен своего Telegram-бота
  chat_id: 7907269451                  # число, полученное через @userinfobot или Telethon

bonkbot:
  enabled: true
  session_file: "bonkbot.session"
  username: "@bonkbot_bot"    # username BonkBot или твоего аккаунта

